// add todo
export const REQUESTED_ADD_TODO = 'REQUESTED_ADD_TODO';
export const REQUESTED_SUCCEEDED_ADD_TODO = 'REQUESTED_SUCCEEDED_ADD_TODO';
export const REQUESTED_FAILED_ADD_TODO = 'REQUESTED_FAILED_ADD_TODO';
export const FETCHED_ADD_TODO = 'FETCHED_ADD_TODO';

// show todos
export const REQUESTED_TODOS = 'REQUESTED_TODOS';
export const REQUESTED_SUCCEEDED_TODOS = 'REQUESTED_SUCCEEDED_TODOS';
export const REQUESTED_FAILED_TODOS = 'REQUESTED_FAILED_TODOS';
export const FETCHED_TODOS = 'FETCHED_TODOS';

// complete todo
export const REQUESTED_COMPLETE_TODO = 'REQUESTED_COMPLETE_TODO';
export const REQUESTED_SUCCEEDED_COMPLETE_TODO =
  'REQUESTED_SUCCEEDED_COMPLETE_TODO';
export const REQUESTED_FAILED_COMPLETE_TODO = 'REQUESTED_FAILED_COMPLETE_TODO';
export const FETCHED_COMPLETE_TODO = 'FETCHED_COMPLETE_TODO';

// delete todo
export const REQUESTED_DELETE_TODO = 'REQUESTED_DELETE_TODO';
export const REQUESTED_SUCCEEDED_DELETE_TODO =
  'REQUESTED_SUCCEEDED_DELETE_TODO';
export const REQUESTED_FAILED_DELETE_TODO = 'REQUESTED_FAILED_DELETE_TODO';
export const FETCHED_DELETE_TODO = 'FETCHED_DELETE_TODO';

// filters

// search todos
export const FETCHED_SEARCH_TODOS = 'FETCHED_SEARCH_TODOS';
export const REQUESTED_SEARCH_TODO = 'REQUESTED_SEARCH_TODO';
export const REQUESTED_SUCCEEDED_SEARCH_TODO =
  'REQUESTED_SUCCEEDED_SEARCH_TODO';
export const REQUESTED_FAILED_SEARCH_TODO = 'REQUESTED_FAILED_SEARCH_TODO';

// all todos
export const REQUESTED_ALL_TODO = 'REQUESTED_ALL_TODO';
export const REQUESTED_SUCCEEDED_ALL_TODO = 'REQUESTED_SUCCEEDED_ALL_TODO';
export const REQUESTED_FAILED_ALL_TODO = 'REQUESTED_FAILED_ALL_TODO';
export const FETCHED_ALL_TODOS = 'FETCHED_ALL_TODOS';

// action todos
export const REQUESTED_ACTION_TODOS = 'REQUESTED_ACTION_TODOS';
export const REQUESTED_SUCCEEDED_ACTION_TODOS =
  'REQUESTED_SUCCEEDED_ACTION_TODOS';
export const REQUESTED_FAILED_ACTION_TODOS = 'REQUESTED_FAILED_ACTION_TODOS';
export const FETCHED_ACTION_TODOS = 'FETCHED_ACTION_TODOS';

// done todos
export const REQUESTED_DONE_TODOS = 'REQUESTED_DONE_TODOS';
export const REQUESTED_SUCCEEDED_DONE_TODOS = 'REQUESTED_SUCCEEDED_DONE_TODOS';
export const REQUESTED_FAILED_DONE_TODOS = 'REQUESTED_FAILED_DONE_TODOS';
export const FETCHED_DONE_TODOS = 'FETCHED_DONE_TODOS';
