// login user
export const REQUESTED_LOGIN_USER = 'REQUESTED_LOGIN_USER';
export const REQUESTED_SUCCEEDED_LOGIN_USER = 'REQUESTED_SUCCEEDED_LOGIN_USER';
export const REQUESTED_FAILED_LOGIN_USER = 'REQUESTED_FAILED_LOGIN_USER';
export const FETCHED_LOGIN_USER = 'FETCHED_LOGIN_USER';

// register user
export const REQUESTED_REGISTER_USER = 'REQUESTED_REGISTER_USER';
export const REQUESTED_SUCCEEDED_REGISTER_USER =
  'REQUESTED_SUCCEEDED_REGISTER_USER';
export const REQUESTED_FAILED_REGISTER_USER = 'REQUESTED_FAILED_REGISTER_USER';
export const FETCHED_REGISTER_USER = 'FETCHED_REGISTER_USER';

// show info current User
export const REQUESTED_USER = 'REQUESTED_USER';
export const REQUESTED_SUCCEEDED_USER = 'REQUESTED_SUCCEEDED_USER';
export const REQUESTED_FAILED_USER = 'REQUESTED_FAILED_USER';
export const FETCHED_USER = 'FETCHED_USER';
